### ISSUE TITLE
`depcheck version` fails with uninitialized constant error

### ISSUE THREAD

**Issue by ldiqual** [wojteklu/depcheck#5]
```
$ depcheck version
/Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/depcheck-0.1.0/lib/depcheck/command/version_command.rb:4:in `execute': uninitialized constant Depcheck::VERSION (NameError)
        from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
        from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
        from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
        from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
        from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/depcheck-0.1.0/bin/depcheck:16:in `<top (required)>'
        from /Users/ldiqual/.rbenv/versions/2.3.0/bin/depcheck:23:in `load'
        from /Users/ldiqual/.rbenv/versions/2.3.0/bin/depcheck:23:in `<main>'
```

**Comment by wojteklu** [comment]
@ldiqual I fixed the problem. Please check the newest version. Thanks!
